### ISSUE TITLE
Tool addition: Bulk Reviewer

### ISSUE THREAD

**Issue by kamwoods** [BitCurator/bitcurator-salt#22]
Todo: Test and add Bulk Reviewer (https://github.com/bulk-reviewer/bulk-reviewer) as a default tool in the environment.

Rationale: Bulk Reviewer is used by some community members working on air-gapped, locked down systems. It would be useful for them to have it in by default.

Testing to date: I've done minor testing, initially verified that Bulk Reviewer (the prebuilt AppImage at https://github.com/bulk-reviewer/bulk-reviewer/releases/tag/v0.3.1) runs in 22.04 and talks to the versions of bulk_extractor and tsk in BC.

Essentially, add a state to pull BulkReviewer-0.3.1.AppImage (or appimage from latest release?), place it in /usr/local/bin, add a launch entry in the Forensics and Reporting submenu titled "Bulk Reviewer".

**Comment by digitalsleuth** [comment]
Easy enough. I'll take a look at it shortly!

**Comment by kamwoods** [comment]
Thanks for the pr. Tested and appears good. As you likely saw I merged and made a release. Updated the docs, and finally built a .ova for the 4.3.0 release, as well. Closing.
