### ISSUE TITLE
Fix: get primary group for user instead of using group {{ name }}

### ISSUE THREAD

**Issue by kamwoods** [BitCurator/bitcurator-salt#25]
Various states assume the primary group is the same as the username, for example in dot-local.sls:

/home/{{ user }}/.local:
  file.recurse:
    - source: salt://bitcurator/env/.local
    - user: {{ user }}
    - group: {{ user }}

This is true for the default configuration of local users created in Ubuntu. However, "group: {{ user }}" may not exist if the user is created or managed according to an external policy. Instead, get the group name associated with the gid for the specified user, and use that.

**Comment by digitalsleuth** [comment]
I have an idea or two on how this can be accomplished and am testing them now. 
I should have a PR done up this evening after tests are complete.

**Comment by kamwoods** [comment]
Resolved in https://github.com/BitCurator/bitcurator-salt/pull/26
