### ISSUE TITLE
Installation fails due to outdated libuna-alpha release

### ISSUE THREAD

**Issue by dolnack** [BitCurator/bitcurator-salt#43]
Hi folks,

My BitCurator install is failing, and it looks like it's due to an outdated libuna release: 

  file_|-libuna-source_|-/tmp/libuna-alpha-20220611.tar.gz_|-managed:
    __id__: libuna-source
    __run_num__: 250
    __sls__: bitcurator.tools.libuna
    changes: {}
    comment: 'Failed to cache https://github.com/libyal/libuna/releases/download/20220611/libuna-alpha-20220611.tar.gz:
      Error: HTTP 404: Not Found reading /libyal/libuna/releases/download/20220611/libuna-alpha-20220611.tar.gz'
    duration: 116.787
    name: /tmp/libuna-alpha-20220611.tar.gz
    result: false

The 20220611 version has been removed: https://github.com/libyal/libuna/releases

I've attached the full install log here: [saltstack.log](https://github.com/BitCurator/bitcurator-salt/files/14195948/saltstack.log)

Is there a way I could modify a config file somewhere to point to the latest release source during the bitcurator install?

**Comment by kamwoods** [comment]
Libuna is not needed and should have been removed for the 4.x releases. It also looks like several other packages are broken at this point. I'll look into it.

**Comment by kamwoods** [comment]
@dolnack A new release (4.4.4) is now available which removes libuna, adds a missing libre2-dev requirement for the latest bulk_extractor, and updates bulk_extractor to the official 2.1.0 release.

**Comment by dolnack** [comment]
Thanks so much, @kamwoods ! Ran the install again and it finished without error and everything's working beautifully. I really appreciate the quick reply and turnaround!
