### ISSUE TITLE
Timezone changes to UTC after install. 

### ISSUE THREAD

**Issue by jesswhyte** [BitCurator/bitcurator-salt#8]
After install, timezone changes to UTC (see timezone.sls). While this is appropriate for forensics or e-discovery, it might be confusing for others. E.g. we changed it back to our timezone.

**Comment by digitalsleuth** [comment]
Hi @jesswhyte, typically UTC is a default for most systems of this kind, and is pretty much a "middle ground" for all of the choices available. However I can understand your point. Did you have a thought as to how you would like to see this resolved?

**Comment by jesswhyte** [comment]
Want to leave it as-is, and if other users raise it as an issue, maybe leave out the timezone configuration all together? If nobody else raises it, I'll just take the extra step and reset it :-) ?

**Comment by digitalsleuth** [comment]
Got it, makes sense :)

**Comment by kamwoods** [comment]
For now we'll put a comment in the upcoming quickstart guide for the 3.x releases, to draw folks attention to it.
