### ISSUE TITLE
Update for jammy deployment

### ISSUE THREAD

**Issue by kamwoods** [BitCurator/bitcurator-salt#9]
Running (non-comprehensive) list of reminders / thoughts related to updates needed for jammy:

- bctools.sls in /Tools can simply be removed; these tools are end of life (potential rewrite in Qt6 should the community indicate a strong desire for it in the future)
- Update key for Siegfried repo
- No jammy release file for sift and gift currently...alternate sources for liblightgrep + bulk_extractor? Thoughts about building bulk_extractor 2.0.0 from release tarball?
- dbus-x11 package needed for 22.04

**Comment by digitalsleuth** [comment]
Final testing ongoing right now. Minor compatibility issue with libappindicator3 on Jammy.
Removed SIFT, left GIFT as it still provides bulk_extractor, but will test the build install then remove GIFT.

Installing sleuthkit from the apt repo doesn't provide the VMDK and VHD mount options on Focal, only on Jammy. I'll remove the build option state in favor of the apt package install if that's preferable.

**Comment by digitalsleuth** [comment]
While I'm finalizing the states, is there a plan to continue to support Bionic, or would you like support for Bionic removed?

**Comment by kamwoods** [comment]
Removing bionic support is ok. The documentation is all going to convey that this is intended for focal and jammy, with strong hinting that new installs should be on jammy.

**Comment by digitalsleuth** [comment]
Okay, everything is ready to go, with one exception. On Jammy, there is currently no way to have a transparent background image AND a solid color behind it, and have the image be properly centered. I can set the background image, or the solid color, but not both like in focal. The reference issue is being tracked through GNOME [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5428).

## ZOOM - Doesn't show background color
![Jammy-Background-Zoom](https://user-images.githubusercontent.com/62841822/192123287-8f599b7e-d3ae-49f9-a1c5-0261e9a14fd9.png)  

## CENTERED - Doesn't show background color
![Jammy-Background-Centered](https://user-images.githubusercontent.com/62841822/192123292-8f0fd733-1396-4ea2-952a-fbcef0015f68.png)

## WALLPAPER - Shows background color, but off-centered background image
![Jammy-Background-Wallpaper](https://user-images.githubusercontent.com/62841822/192123303-cd569a51-355b-4c78-91c3-6ab2088beaeb.png)

Just let me know what your preference is for Jammy and I can duplicate it in Focal if you'd like. Once this decision is made, Jammy support is ready.

**Comment by kamwoods** [comment]
Wallpaper is fine, for now, even with the wonky offcentering. I have no preference but we've asked before and people in our user group doing presentations (projectors, demoing tools in classes etc) appear to like a colored background significantly more than a black one. I'll make a note to reassess / check in on that GNOME issue later.

**Comment by kamwoods** [comment]
I also should have added earlier, although I assume you just went ahead - apt install for sleuthkit is fine. Our (much) earlier decisions around sleuthkit + libewf builds were based on keeping the BitCurator Reporting Tool functional. That's no longer an issue, for the reasons I stated earlier. I can put a note in the docs regarding deploying on jammy to ensure those who might need to parse these virtual images are aware.

**Comment by digitalsleuth** [comment]
[PR submitted](https://github.com/BitCurator/bitcurator-salt/pull/10), awaiting approval!

**Comment by digitalsleuth** [comment]
I'll keep an eye out for the release and run a full check using the CLI and updated state release. I'm positive there won't be an issue, but I'll do the due diligence anyways :)
